Repository openshift-service-mesh/istio, pull requests merged in 2025-05, with the labels that each got.

#366 small fix to get latest istio version
  prow/setup/sail-operator-setup.sh
Labels: okay to merge, size/XS

#369 fix for release directory structure to patch config
  prow/setup/sail-operator-setup.sh
Labels: size/XS

#371 change timeout value 2h if test is running on sail-operator
  prow/integ-suite-ocp.sh
Labels: size/S

#373 modify cleanup function with wait
  prow/setup/sail-operator-setup.sh
Labels: okay to merge, size/S

#374 Revert "Add retry timeouts delay for AWS LB (#227)"
  tests/integration/pilot/common/routing.go
Labels: okay to merge, size/S

#379 Sync upstream 1.24.5
  .devcontainer/devcontainer.json
  .gitignore
  Makefile.core.mk
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/install/cniconfig.go
  cni/pkg/install/cniconfig_test.go
  cni/pkg/install/testdata/bridge.conf.golden
  cni/pkg/install/testdata/istio-cni.conf
  cni/pkg/install/testdata/list-with-istio.conflist.golden
  cni/pkg/install/testdata/list.conflist.golden
  cni/pkg/plugin/plugin.go
  cni/test/testdata/expected/10-calico.conflist-istioconfig
  cni/test/testdata/expected/YYY-istio-cni.conf
  cni/test/testdata/expected/minikube_cni.conflist.expected
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  istio.deps
  istioctl/pkg/writer/ztunnel/configdump/api.go
  istioctl/pkg/writer/ztunnel/configdump/certificates.go
  licenses/gopkg.in/natefinch/lumberjack.v2/LICENSE
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  pilot/pkg/networking/core/httproute.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_cache.go
  pilot/pkg/networking/core/route/route_test.go
  pkg/log/options.go
  pkg/log/uds.go
  releasenotes/notes/55304.yaml
  releasenotes/notes/grpc-inbound-retry.yaml
  releasenotes/notes/rds-cache-alias.yaml
  security/pkg/server/ca/server.go
Labels: size/L, okay to merge

#383 Sync upstream 1.24.5
  .devcontainer/devcontainer.json
  .gitignore
  Makefile.core.mk
  cni/pkg/cmd/root.go
  cni/pkg/config/config.go
  cni/pkg/constants/constants.go
  cni/pkg/install/cniconfig.go
  cni/pkg/install/cniconfig_test.go
  cni/pkg/install/testdata/bridge.conf.golden
  cni/pkg/install/testdata/istio-cni.conf
  cni/pkg/install/testdata/list-with-istio.conflist.golden
  cni/pkg/install/testdata/list.conflist.golden
  cni/pkg/plugin/plugin.go
  cni/test/testdata/expected/10-calico.conflist-istioconfig
  cni/test/testdata/expected/YYY-istio-cni.conf
  cni/test/testdata/expected/minikube_cni.conflist.expected
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  istio.deps
  istioctl/pkg/writer/ztunnel/configdump/api.go
  istioctl/pkg/writer/ztunnel/configdump/certificates.go
  licenses/gopkg.in/natefinch/lumberjack.v2/LICENSE
  manifests/charts/istio-cni/templates/configmap-cni.yaml
  manifests/charts/istio-cni/templates/daemonset.yaml
  pilot/pkg/networking/core/httproute.go
  pilot/pkg/networking/core/route/route.go
  pilot/pkg/networking/core/route/route_cache.go
  pilot/pkg/networking/core/route/route_test.go
  pkg/log/options.go
  pkg/log/uds.go
  releasenotes/notes/55304.yaml
  releasenotes/notes/grpc-inbound-retry.yaml
  releasenotes/notes/rds-cache-alias.yaml
  security/pkg/server/ca/server.go
Labels: tide/merge-method-merge, okay to merge

#384 bump golang.org/x/net (#56238)
  go.mod
  go.sum
Labels: size/M, okay to merge

#385 Fix listener addr duplication for dualStack svc with IPv6 as primary …
  pilot/pkg/model/service.go
  pilot/pkg/model/service_test.go
Labels: size/L, okay to merge

#390 Add ambient test flow
  prow/integ-suite-ocp.sh
Labels: okay to merge, size/S
