Repository openshift-service-mesh/istio, pull requests merged in 2025-09, with the labels that each got.

#479 Move "meshConfig" values out of gateway manifests
  prow/config/sail-operator/egress-gateway-values.yaml
  prow/config/sail-operator/ingress-gateway-values.yaml
Labels: okay to merge, size/XS

#484 Fixing lint warnings in our ocp scripts
  prow/integ-suite-ocp.sh
  prow/setup/ocp_setup.sh
  prow/setup/sail-operator-setup.sh
Labels: okay to merge, size/S

#488 Sync upstream 1.26.4
  .devcontainer/devcontainer.json
  Makefile.core.mk
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  docker/iptables.yaml
  go.mod
  go.sum
  istio.deps
  licenses/github.com/santhosh-tekuri/jsonschema/v6/LICENSE
  licenses/github.com/xeipuuv/gojsonpointer/NONE
  licenses/github.com/xeipuuv/gojsonreference/NONE
  licenses/github.com/xeipuuv/gojsonschema/NONE
  manifests/charts/gateway/values.schema.json
  pilot/pkg/networking/core/listener_builder.go
  pilot/pkg/networking/core/listener_builder_test.go
  pkg/revisions/tag_watcher.go
  releasenotes/notes/56626.yaml
  releasenotes/notes/56767.yaml
  releasenotes/notes/57354.yaml
  releasenotes/notes/57528.yaml
  tests/binary/binaries_test.go
  tests/integration/helm/install_test.go
  tools/istio-iptables/pkg/capture/helper.go
  tools/istio-iptables/pkg/capture/run_linux_test.go
Labels: tide/merge-method-merge, okay to merge, size/XL

#499 [Release 1.26] move mesh config values out of gateway manifests
  prow/config/sail-operator/egress-gateway-values.yaml
  prow/config/sail-operator/ingress-gateway-values.yaml
Labels: size/XS

#500 [release-1.27] Move "meshConfig" values out of gateway manifests (#479)
  prow/config/sail-operator/egress-gateway-values.yaml
  prow/config/sail-operator/ingress-gateway-values.yaml
Labels: okay to merge, size/XS

#489 Gateway API Inference Extension v1.0
  go.mod
  go.sum
  licenses/github.com/cenkalti/backoff/v5/LICENSE
  manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  pilot/pkg/config/kube/crdclient/types.gen.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/inferencepool_collection.go
  pilot/pkg/config/kube/gateway/inferencepool_status_test.go
  pilot/pkg/config/kube/gateway/inferencepool_test.go
  pilot/pkg/config/kube/gateway/route_collections.go
  pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml
  pilot/pkg/config/kube/gateway/testdata/reference-policy-inferencepool.status.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-inferencepool.yaml
  pkg/config/schema/collections/collections.gen.go
  pkg/config/schema/gvk/resources.gen.go
  pkg/config/schema/gvr/resources.gen.go
  pkg/config/schema/kubeclient/resources.gen.go
  pkg/config/schema/kubetypes/resources.gen.go
  pkg/config/schema/metadata.yaml
  pkg/kube/client.go
  releasenotes/notes/57219-final.yaml
  releasenotes/notes/57219-rc2.yaml
  releasenotes/notes/57219.yaml
  releasenotes/notes/57472.yaml
  tests/integration/pilot/testdata/gateway-api-inference-extension-crd.yaml
Labels: size/XXL, okay to merge

#503 Add gotestsum option for integration test
  prow/integ-suite-ocp.sh
Labels: okay to merge, size/S

#501 Do not use a default revision in gatewayinstance tests
  tests/integration/pilot/gatewayinstance/main_test.go
Labels: okay to merge, size/XS

#505 [Release 1.26] Add gotestsum option for integration test execution which is suitable…
  prow/integ-suite-ocp.sh
Labels: okay to merge, size/S

#504 Implement cluster operator stability check
  prow/integ-suite-ocp.sh
Labels: size/M, okay to merge, cherrypick/release-1.26, cherrypick/release-1.24, cherrypick/release-1.27
