Repository openshift-service-mesh/istio, pull requests merged in 2025-06, with the labels that each got.

#404 Sync upstream 1.24.6
  Makefile.core.mk
  istio.deps
  manifests/charts/istio-control/istio-discovery/templates/revision-tags.yaml
  pilot/pkg/networking/core/cluster.go
  pkg/config/validation/validation.go
  pkg/config/validation/validation_test.go
  pkg/test/framework/test.go
  releasenotes/notes/55567.yaml
  releasenotes/notes/make-revision-tag-work-when-istiod-remote-is-enabled.yaml
  tests/integration/security/sds_ingress/quic/ingress_test.go
  tests/integration/security/sds_ingress/util/util.go
Labels: tide/merge-method-merge, size/M, okay to merge

#418 [release-1.26] Merge 1.26.2
  Makefile.core.mk
  go.mod
  go.sum
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  pilot/pkg/config/kube/gateway/backend_policies.go
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/conversion.go
  pilot/pkg/config/kube/gateway/gatewayclass.go
  pilot/pkg/config/kube/gateway/gatewayclass_collection.go
  pilot/pkg/config/kube/gateway/model.go
  pilot/pkg/config/kube/gateway/route_collections.go
  pilot/pkg/config/kube/gateway/status.go
  pilot/pkg/config/kube/gateway/status_test.go
  pilot/pkg/config/kube/gateway/testdata/delegated.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/grpc.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/isolation.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-service.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-binding.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/serviceentry.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
  pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden
  pilot/pkg/status/manager.go
  pkg/config/model.go
  pkg/kube/inject/inject_test.go
  pkg/kube/inject/testdata/inject/hello-openshift-tproxy.yaml
  pkg/kube/inject/testdata/inject/hello-openshift-tproxy.yaml.injected
  pkg/kube/krt/collection.go
  pkg/kube/krt/index.go
  pkg/kube/krt/internal.go
  pkg/kube/krt/static.go
  pkg/kube/krt/status.go
  pkg/kube/krt/util.go
  pkg/test/framework/components/crd/gateway.go
  pkg/test/framework/components/istio/config.go
  pkg/test/framework/components/istio/flags.go
  releasenotes/notes/56577.yaml
  tests/integration/README.md
  tests/integration/ambient/registry_setup_test.go
  tools/build-base-images.sh
Labels: tide/merge-method-merge, size/XXL, okay to merge

#412 [release-1.26] tls: add PQC compliance policy (#56331)
  pkg/features/security.go
  pkg/model/fips.go
  releasenotes/notes/pqc.yaml
Labels: size/M, okay to merge
