Repository openshift-service-mesh/istio, pull requests merged in 2025-04, with the labels that each got.

#333 [release-1.24] OSSM-8206 istiod ca: custom ConfigMap name for CA root cert
  manifests/charts/gateways/istio-egress/templates/deployment.yaml
  manifests/charts/gateways/istio-ingress/templates/deployment.yaml
  manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
  manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
  manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml
  manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
  manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
  manifests/charts/ztunnel/templates/daemonset.yaml
  operator/pkg/apis/values_types.pb.go
  operator/pkg/apis/values_types.proto
  pilot/pkg/features/experimental.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
  pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
  pkg/kube/inject/testdata/inputs/custom-template.yaml.43.template.gen.yaml
  pkg/kube/inject/testdata/inputs/default.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.15.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.14.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.10.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.19.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello-probes.yaml.17.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.11.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.16.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
  pkg/kube/inject/testdata/inputs/hello.yaml.9.template.gen.yaml
  pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
  pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.template.gen.yaml
  pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.33.template.gen.yaml
  pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
  pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
  pkg/test/framework/components/echo/common/deployment/echos.go
  pkg/test/framework/components/echo/common/deployment/namespace.go
  releasenotes/notes/53385.yaml
  tests/integration/pilot/multiplecontrolplanes/main_test.go
Labels: size/L, okay to merge

#338 [release-1.24] OSSM-8825 add integration test for gateway instance
  tests/integration/pilot/gatewayinstance/main_test.go
Labels: size/L, okay to merge

#335 [release-1.24] OSSM-9076 Enable CA Bundle injection in only Gateway Namespaces
  pilot/pkg/bootstrap/configcontroller.go
  pilot/pkg/bootstrap/server.go
  pilot/pkg/config/kube/gateway/gateway_ca_controller.go
  pilot/pkg/config/kube/gateway/gateway_ca_controller_test.go
  pilot/pkg/features/experimental.go
  pilot/pkg/leaderelection/leaderelection.go
  tests/integration/pilot/gatewayinstance/main_test.go
Labels: size/L, okay to merge, ok-to-test

#300 Modifications to Run integration Tests With Sail Operator
  prow/config/sail-operator/egress-gateway-values.yaml
  prow/config/sail-operator/ingress-gateway-values.yaml
  prow/config/sail-operator/istio-cni.yaml
  prow/config/sail-operator/validatingwebhook.yaml
  prow/integ-suite-ocp.sh
  prow/setup/ocp_setup.sh
  prow/setup/sail-operator-setup.sh
Labels: size/L, okay to merge

#344 Fix tests resources cleanup for Openshift (#55638)
  pkg/kube/client.go
  pkg/test/framework/components/istio/cleanup.go
  pkg/test/kube/dump.go
  pkg/test/kube/util.go
Labels: size/L, okay to merge

#312 OSSM-8998 Disable istioctl commands with building ldflags
  istioctl/cmd/ossm_custom_cmd.go
  istioctl/cmd/root.go
Labels: size/L, okay to merge

#359 Add copyright banner
  istioctl/cmd/ossm_custom_cmd.go
Labels: okay to merge, size/S

#348 Fixing Failing Converter Tests
  prow/setup/sail-operator-setup.sh
Labels: size/S
