Repository openshift-service-mesh/istio, pull requests merged in 2025-01, with the labels that each got.

#222 [release-1.24] Fixes to make tests work in our prow
  common/scripts/kind_provisioner.sh
  prow/integ-suite-kind.sh
  tests/integration/helm/install_test.go
  tests/integration/helm/upgrade/helm_upgrade_test.go
  tools/istio-iptables/pkg/capture/run_test.go
Labels: okay to merge, size/S

#225 Use our proxy
  bin/init.sh
  istio.deps
  pilot/docker/Dockerfile.proxyv2
  pkg/config/security/security.go
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_8
  pkg/test/framework/components/echo/config.go
  prow/integ-suite-kind.sh
  prow/lib.sh
  tests/integration/security/external_ca/main_test.go
  tests/integration/security/sds_ingress/quic/ingress_test.go
Labels: size/M, okay to merge

#266 Enable istioctl related ambient commands
  istioctl/cmd/root.go
Labels: size/XS
