Repository openshift-service-mesh/istio, pull requests merged in 2025-07, with the labels that each got.

#421 prow: revert patching TestGatewayConformance
  prow/config/sail-operator/istio-gw-api-coredns-fix.patch
  prow/setup/sail-operator-setup.sh
Labels: okay to merge, size/XL

#416 tests: do not skip TPROXY sidecars
  prow/integ-suite-ocp.sh
Labels: okay to merge, size/XS

#423 Add Ambient Gateway API test flow
  prow/integ-suite-ocp.sh
Labels: size/M, okay to merge

#433 [release-1.26] (gaie): Fixups from master PR (#56899)
  pilot/pkg/config/kube/gateway/controller.go
  pilot/pkg/config/kube/gateway/inferencepool_collection.go
Labels: size/M

#436 Add Ambient flow to Sail Operator Control Plane deploy for Integ tests
  prow/config/sail-operator/ztunnel.yaml
  prow/setup/sail-operator-setup.sh
Labels: size/M, okay to merge

#441 release-1.26 Gateway Conformance Test Fixes
  pkg/test/framework/resource/flags.go
  pkg/test/framework/resource/settings.go
  prow/config/sail-operator/istio-gw-api-coredns-fix.patch
  prow/integ-suite-ocp.sh
  prow/setup/ocp_setup.sh
  tests/integration/pilot/gateway_conformance_test.go
Labels: tide/merge-method-merge, size/XL

#446 manifests: add NetworkPolicy to istio-cni chart
  manifests/charts/istio-cni/templates/networkpolicy.yaml
  releasenotes/notes/56877.yaml
Labels: size/M, okay to merge

#450 security suite control plane parameters
  prow/setup/sail-operator-setup.sh
Labels: size/M

#453 Fix the proxy image to work with new proxy binary
  istio.deps
  pilot/docker/Dockerfile.proxyv2
  pkg/test/echo/docker/Dockerfile.app_sidecar_centos_8
Labels: size/M, okay to merge

#457 Modify Prow Sail Operator script cleanup step
  prow/setup/sail-operator-setup.sh
Labels: okay to merge, size/S
