Repository openshift-service-mesh/istio, pull requests merged in 2025-03, with the labels that each got.

#307 Fix CVE-2025-22868
  go.mod
  go.sum
Labels: okay to merge, size/S

#311 Update some examples to use quay.io/sail-dev instead of docker
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-psa.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/helloworld/helloworld-dual-stack.yaml
  samples/helloworld/helloworld.yaml
  samples/httpbin/httpbin-nodeport.yaml
  samples/httpbin/httpbin.yaml
  samples/tcp-echo/tcp-echo-dual-stack.yaml
  samples/tcp-echo/tcp-echo-ipv4.yaml
  samples/tcp-echo/tcp-echo-ipv6.yaml
  samples/tcp-echo/tcp-echo-services.yaml
  samples/tcp-echo/tcp-echo.yaml
Labels: size/M

#313 [release-1.24] Update some examples to use quay.io/sail-dev instead of docker
  samples/bookinfo/platform/kube/bookinfo-db.yaml
  samples/bookinfo/platform/kube/bookinfo-details-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-details.yaml
  samples/bookinfo/platform/kube/bookinfo-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-psa.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-dualstack.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
  samples/bookinfo/platform/kube/bookinfo-ratings.yaml
  samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
  samples/bookinfo/platform/kube/bookinfo.yaml
  samples/helloworld/helloworld-dual-stack.yaml
  samples/helloworld/helloworld.yaml
  samples/httpbin/httpbin-nodeport.yaml
  samples/httpbin/httpbin.yaml
  samples/tcp-echo/tcp-echo-dual-stack.yaml
  samples/tcp-echo/tcp-echo-ipv4.yaml
  samples/tcp-echo/tcp-echo-ipv6.yaml
  samples/tcp-echo/tcp-echo-services.yaml
  samples/tcp-echo/tcp-echo.yaml
Labels: size/M

#319 Update sleep to use quay.io/sail-dev
  samples/curl/curl.yaml
  samples/sleep/sleep.yaml
Labels: okay to merge, size/XS

#332 [release-1.24] Update proxy
  istio.deps
Labels: okay to merge, size/XS
